namespace Marquee.Infrastructure.Observability;

/// <summary>
/// Names for the metadata Marquee moves between processes. Kept as constants in one place because
/// the same string has to match on an HTTP header, a RabbitMQ message header, and a log property —
/// three layers that never see each other's code.
/// </summary>
public static class MarqueeHeaders
{
    /// <summary>
    /// The correlation id, as an HTTP request/response header and as a message header on the queue.
    /// </summary>
    public const string CorrelationId = "X-Correlation-Id";

    /// <summary>The log property name. Kept without the "X-" so log queries read naturally.</summary>
    public const string CorrelationIdProperty = "CorrelationId";
}

/// <summary>
/// The correlation id for whatever this process is currently doing — one HTTP request, one consumed
/// message, one scheduler job.
///
/// It is deliberately ambient (<see cref="AsyncLocal{T}"/>) rather than a constructor parameter. The
/// id has to reach the point where a message is published, and that point sits several layers below
/// the code that knows the id: a controller calls a service, which calls the opener, which publishes.
/// Threading a string through all of those signatures would put an observability concern into the
/// domain-facing API of every one of them.
///
/// <para>
/// <b>Why this exists when OpenTelemetry already produces a TraceId.</b> The trace id is generated by
/// the tracing stack and is meaningless outside it: if sampling drops a trace, or the collector is
/// down, the id refers to nothing. The correlation id is accepted from the caller when they supply
/// one, so a client, a load test, or a support ticket can name a journey and have that exact string
/// appear in both services' logs. Both are logged — see the observability doc for how they pair up.
/// </para>
///
/// <para>
/// <b>AsyncLocal semantics that matter here.</b> A value set inside an async method flows *down* into
/// everything that method awaits, but does not flow back *up* to its caller. Every setter below is
/// therefore at the top of a scope that encloses all the work it should label: the API middleware
/// wraps the whole request, the consume filter wraps the whole message handling.
/// </para>
/// </summary>
public static class CorrelationIdContext
{
    private static readonly AsyncLocal<string?> Current = new();

    /// <summary>The current correlation id, or null when nothing has set one.</summary>
    public static string? Value => Current.Value;

    /// <summary>
    /// Sets the correlation id for the enclosing scope and restores the previous value on dispose.
    /// Restoring matters for the worker, where one thread handles many messages in sequence — without
    /// it, a message that set no id would inherit the previous message's.
    /// </summary>
    public static IDisposable Push(string correlationId)
    {
        var previous = Current.Value;
        Current.Value = correlationId;
        return new Scope(previous);
    }

    /// <summary>
    /// A new id, in the same shape this codebase uses for other opaque identifiers ("N" format, no
    /// dashes). Used when a caller supplies none.
    /// </summary>
    public static string NewId() => Guid.NewGuid().ToString("N");

    private sealed class Scope(string? previous) : IDisposable
    {
        private bool _disposed;

        public void Dispose()
        {
            if (_disposed)
                return;
            _disposed = true;
            Current.Value = previous;
        }
    }
}
